# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'TextToSpeech' do
    
    config = use_native_modules!

    use_react_native!(:path => config["reactNativePath"])


    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    
    #use_flipper!
    #post_install do |installer|
     # flipper_post_install(installer)
    #end

end
